#!/usr/bin/env python3
"""cubefree.py - the z2n campaign's one instrument.

WHAT IT COMPUTES
  `f(n)`, the largest cube-free subset of `Z_{2^n}`, and the extremal sets that
  achieve it. Cube-free means no `x, y, z` with all seven of `x`, `y`, `z`,
  `x+y`, `y+z`, `z+x`, `x+y+z` in the set.

TWO INDEPENDENT ROUTES, WHICH IS THE POINT
  `f_sat(n)`     a SAT encoding, one variable per residue, one clause per
                 minimal cube, plus a cardinality constraint. Decides
                 `f(n) >= t` and `f(n) >= t+1`.
  `f_brute(n)`   exhaustive search over subsets, with the layer structure used
                 only to order the search. Feasible to n = 4 and no further.

  They share only the cube enumerator, so an error in the SAT encoding or in
  the cardinality constraint shows up as disagreement. The enumerator itself
  is the common-mode risk. `verify()` closes that risk by re-checking directly
  that every returned set satisfies the definition.

THE PLANTED-SET TEST, AND WHY IT IS NOT A PLANTED ZERO
  The zeta campaign planted a synthetic zero into a continuous sum. There is no
  continuous sum here. The discrete analog is to plant a SET: build one that
  is cube-free by construction and one that provably is not, and confirm the
  instrument classifies both correctly. An instrument that says "cube-free" to
  everything reproduces every known `f(n)` as a lower bound and is worthless.

USAGE
  cubefree.py --validate        two routes agree on f(1..4), emits a verdict
  cubefree.py --plant           planted-set test, emits a verdict
  cubefree.py --known           reproduce f(1..6) by SAT, emits a verdict
  cubefree.py --control         the hold-out and over-certification controls
  cubefree.py --decide N T      is there a cube-free set of size >= T in Z_2^N
"""
import argparse
import itertools
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
import numkit  # noqa: E402  must precede numpy, which pysat may pull in

numkit.mem_guard()

from pysat.card import CardEnc, EncType  # noqa: E402
from pysat.formula import CNF  # noqa: E402
from pysat.solvers import Cadical195  # noqa: E402

# The known values, from the bench. Every one settled by SAT under two
# independent encodings that agree, each optimum re-verified by triple scan.
KNOWN = {1: 1, 2: 2, 3: 5, 4: 10, 5: 20, 6: 40}


def cubes(n):
    """Every minimal cube as a frozenset of residues.

    A `cube` here is the seven-element image {x, y, z, x+y, y+z, z+x, x+y+z}.
    Degenerate choices of x, y, z collapse it to fewer elements, and those
    degenerate ones carry the 2/3 bound, so they are kept rather than filtered.
    """
    N = 1 << n
    out = set()
    for x in range(N):
        for y in range(N):
            for z in range(N):
                out.add(frozenset({x, y, z, (x + y) % N, (y + z) % N,
                                   (z + x) % N, (x + y + z) % N}))
    return out


def is_cube_free(n, A):
    """Direct check against the definition. No encoding, no solver.

    This is the common-mode guard. Both routes share `cubes()`, so a bug there
    would fool both. This function does not use `cubes()` at all.
    """
    N = 1 << n
    S = set(A)
    for x in S:
        for y in S:
            if (x + y) % N not in S:
                continue
            for z in S:
                if ((y + z) % N in S and (z + x) % N in S
                        and (x + y + z) % N in S):
                    return False
    return True


# --------------------------------------------------------------------------
# route A: SAT
# --------------------------------------------------------------------------

def decide_sat(n, t, cube_set=None):
    """Is there a cube-free A subset of Z_{2^n} with |A| >= t, and 0 not in A?

    Returns (satisfiable, the set or None). Fixing 0 out is without loss: 0 is
    in every cube generated by x = y = z = 0, so no cube-free set contains it.
    """
    N = 1 << n
    lits = list(range(2, N + 1))

    # CardEnc.atleast raises `Wrong bound` when the bound exceeds the number of
    # literals, rather than returning an unsatisfiable encoding. At n = 1 there
    # is exactly one free residue, so asking for two is that case. Decide it
    # here: more elements than residues is unsatisfiable, and a non-positive
    # bound is satisfied by the empty set.
    if t > len(lits):
        return False, None
    if t <= 0:
        return True, []

    cnf = CNF()
    cnf.append([-1])                                   # residue 0 is out
    for c in (cube_set if cube_set is not None else cubes(n)):
        cnf.append([-(v + 1) for v in c])              # not all of c in A
    card = CardEnc.atleast(lits=lits, bound=t, top_id=N,
                           encoding=EncType.seqcounter)
    cnf.extend(card.clauses)
    with Cadical195(bootstrap_with=cnf) as s:
        sat = s.solve()
        model = s.get_model() if sat else None
    if not sat:
        return False, None
    return True, sorted(i for i in range(N) if model[i] > 0)


def f_sat(n, lo=None, hi=None):
    """f(n) by SAT: the largest t with `decide_sat(n, t)` satisfiable."""
    N = 1 << n
    cs = cubes(n)
    t = lo if lo is not None else 1
    best, best_set = 0, []
    while t <= (hi if hi is not None else N - 1):
        sat, A = decide_sat(n, t, cs)
        if not sat:
            break
        best, best_set = t, A
        t += 1
    return best, best_set


# --------------------------------------------------------------------------
# route B: exhaustive search, independent of the SAT encoding
# --------------------------------------------------------------------------

def f_brute(n):
    """f(n) by exhaustive search over subsets of Z_{2^n} minus {0}.

    Deliberately naive. Its whole job is to be a route that shares no code with
    the SAT encoding or the cardinality constraint. It is feasible to n = 4,
    where 2^15 = 32768 subsets is nothing, and hopeless beyond.
    """
    N = 1 << n
    residues = list(range(1, N))
    for size in range(N - 1, 0, -1):
        for combo in itertools.combinations(residues, size):
            if is_cube_free(n, combo):
                return size, list(combo)
    return 0, []


# --------------------------------------------------------------------------
# the modes
# --------------------------------------------------------------------------

def mode_validate():
    """Two independent routes, agreeing on every n where both are feasible."""
    rows, all_ok = [], True
    for n in (1, 2, 3, 4):
        a, _ = f_sat(n)
        b, _ = f_brute(n)
        r = numkit.two_routes(a, b, tol=0, label=f"f({n})")
        rows.append([n, a, b, "agree" if r["ok"] else "DISAGREE"])
        all_ok = all_ok and r["ok"]
    numkit.table(Path(__file__).resolve().parents[1] / "tables"
                 / "validate-two-routes.txt",
                 rows, header=["n", "f_sat", "f_brute", "verdict"])
    return numkit.emit({"ok": all_ok, "residual": 0 if all_ok else 1,
                        "routes": "sat,brute", "range": "n=1..4",
                        "text": "SAT and exhaustive search agree on f(1..4)"})


def mode_plant():
    """Planted sets. The instrument must classify both correctly.

    A one-sided instrument passes every reproduction test and is still useless,
    so both directions are checked and both must hold.
    """
    n = 4
    N = 1 << n
    # Cube-free by construction: layers 0 and 2, the extremal shape the bench
    # proved is the only one a union of layers can take.
    planted_free = sorted({x for x in range(1, N) if numkit.layer(x, n) in (0, 2)})
    # Provably not cube-free: the whole group contains every cube there is.
    planted_bad = sorted(range(1, N))

    got_free = is_cube_free(n, planted_free)
    got_bad = is_cube_free(n, planted_bad)

    # And the SAT route must find at least the planted set's size.
    sat_at, _ = decide_sat(n, len(planted_free))
    ok = bool(got_free) and not got_bad and bool(sat_at)
    print(f"planted cube-free set of size {len(planted_free)}: "
          f"classified {'cube-free' if got_free else 'NOT cube-free'}")
    print(f"planted full group of size {len(planted_bad)}: "
          f"classified {'cube-free' if got_bad else 'NOT cube-free'}")
    print(f"SAT finds a set of size {len(planted_free)}: {sat_at}")
    return numkit.emit({
        "ok": ok, "residual": 0 if ok else 1,
        "planted_size": len(planted_free),
        "text": ("the instrument accepts a planted cube-free set, rejects the "
                 "full group, and SAT recovers the planted size")})


def mode_known():
    """Reproduce every known f(n). A lower bar than validate, and still needed:
    it is the only check that reaches n = 5 and n = 6."""
    rows, all_ok = [], True
    for n in sorted(KNOWN):
        want = KNOWN[n]
        cs = cubes(n)
        sat_at, A = decide_sat(n, want, cs)
        sat_above, _ = decide_sat(n, want + 1, cs)
        got = want if (sat_at and not sat_above) else None
        verified = is_cube_free(n, A) if A else False
        ok = got == want and verified
        all_ok = all_ok and ok
        rows.append([n, want, got if got is not None else "?",
                     "yes" if verified else "NO", "ok" if ok else "FAIL"])
        print(f"n={n}: SAT at {want}={sat_at}, at {want + 1}={sat_above}, "
              f"witness cube-free={verified}  -> f({n})={got}")
    numkit.table(Path(__file__).resolve().parents[1] / "tables"
                 / "known-f.txt", rows,
                 header=["n", "known", "got", "witness_cubefree", "verdict"])
    return numkit.emit({"ok": all_ok, "residual": 0 if all_ok else 1,
                        "routes": "sat", "range": "n=1..6",
                        "text": "reproduced f(1..6) = 1,2,5,10,20,40"})


def mode_control():
    """The negative controls. Both must hold before anything is claimed.

    1. OVER-CERTIFICATION. The pipeline must not certify a bound BELOW the true
       f(n) at n = 4, 5, 6. Concretely: `decide_sat(n, f(n))` must be
       satisfiable. A pipeline that reports UNSAT there would be claiming a
       better bound than the truth, and its answer at n = 7 would be worthless.
    2. HOLD-OUT. Withhold f(6), fit the pattern 2^(n-1) + 2^(n-3) on f(1..5),
       and check the prediction. f(1..6) is exactly 5/8 * 2^n for n >= 3, so any
       instrument fitted on all of it trivially confirms 5/8. Fitting on a
       subset is the only version of this test that says anything.
    """
    rows, all_ok = [], True

    for n in (4, 5, 6):
        want = KNOWN[n]
        sat_at, A = decide_sat(n, want)
        ok = bool(sat_at) and is_cube_free(n, A)
        all_ok = all_ok and ok
        rows.append(["over-certify", n, f">= {want}", "SAT" if sat_at else "UNSAT",
                     "ok" if ok else "FAIL"])
        print(f"control over-certify n={n}: a set of size {want} exists: "
              f"{sat_at}; witness cube-free: {is_cube_free(n, A) if A else False}")

    fit = [KNOWN[n] for n in (1, 2, 3, 4, 5)]
    predicted = (1 << 5) + (1 << 3)          # 2^(6-1) + 2^(6-3) = 40
    held_out = KNOWN[6]
    hold_ok = predicted == held_out
    all_ok = all_ok and hold_ok
    rows.append(["hold-out", 6, held_out, predicted, "ok" if hold_ok else "FAIL"])
    print(f"control hold-out: fitted 2^(n-1)+2^(n-3) on f(1..5)={fit}, "
          f"predicted f(6)={predicted}, actual {held_out}")

    numkit.table(Path(__file__).resolve().parents[1] / "tables"
                 / "controls.txt", rows,
                 header=["control", "n", "expected", "got", "verdict"])
    return numkit.emit({"ok": all_ok, "residual": 0 if all_ok else 1,
                        "text": ("the pipeline does not over-certify at "
                                 "n=4,5,6 and the hold-out prediction of f(6) "
                                 "is correct")})


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--validate", action="store_true")
    g.add_argument("--plant", action="store_true")
    g.add_argument("--known", action="store_true")
    g.add_argument("--control", action="store_true")
    g.add_argument("--decide", nargs=2, type=int, metavar=("N", "T"))
    a = ap.parse_args()

    if a.validate:
        r = mode_validate()
    elif a.plant:
        r = mode_plant()
    elif a.known:
        r = mode_known()
    elif a.control:
        r = mode_control()
    else:
        n, t = a.decide
        sat, A = decide_sat(n, t)
        verified = is_cube_free(n, A) if A else None

        # `ok` used to be hardcoded True here, which the witness referee found
        # on 2026-08-25. A SAT run whose witness FAILED the direct cube-free
        # scan would still have been recorded as a passing instrument event,
        # so the one check that does not trust the encoding could fail
        # silently. `ok` now carries it.
        #
        # UNSAT is ok:True because there is no witness to verify. That is not
        # the same as the run being trustworthy: an UNSAT here has no
        # certificate, which is why the `unsat_trust` joint of the f(7) claim
        # came back UNCLEAR.
        ok = (bool(verified) if sat else True)

        payload = {"ok": ok, "n": n, "t": t, "sat": bool(sat),
                   "witness_cubefree": verified,
                   "size": len(A) if A else 0,
                   "text": f"f({n}) >= {t} is {bool(sat)}"
                           + ("" if not sat else
                              ("" if verified
                               else "  BUT THE WITNESS IS NOT CUBE-FREE"))}
        if sat and A is not None:
            # Print the witness. A claim that rests on a set and never shows it
            # cannot be checked by hand, which the referee also named.
            payload["witness"] = A
            payload["witness_mod8"] = sorted({v % 8 for v in A})
        r = numkit.emit(payload)
    return 0 if r.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
