#!/usr/bin/env python3
"""Write the prose held inside each mission's json out as `prose.md`, for the linter.

Mission descriptions, theorem titles, and natural language statements are public
prose inside json string literals, invisible to `llm_tics.py --repo`. This
script extracts them so the linter can reach them.

The linter cannot read json directly because the schema knowledge (which keys
are prose) belongs here, and `--check` catches staleness.

    ./extract-prose.py            rewrite every prose.md
    ./extract-prose.py --check    exit 1 if any is stale
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

HEADER = ("<!-- GENERATED by extract-prose.py from this mission's json. Do not\n"
          "edit. Edit the json and regenerate. `--check` fails on drift. -->\n")


def prose_of(slug):
    """Every string of one mission that a human on the platform will read."""
    d = ROOT / slug
    out = [HEADER]

    proposal = json.loads((d / "proposal.json").read_text(encoding="utf-8"))
    out.append(f"# {proposal['name']}\n")
    out.append(proposal["description"])

    items = d / "items"
    if items.is_dir():
        for f in sorted(items.glob("*.json")):
            rec = json.loads(f.read_text(encoding="utf-8"))
            title = rec.get("theorem_title") or rec.get("definition_title", "")
            out.append(f"## {title}\n")
            body = rec.get("natural_language_statement", "")
            if body:
                out.append(body)

    ms = d / "milestones.json"
    if ms.is_file():
        for m in json.loads(ms.read_text(encoding="utf-8"))["milestones"]:
            out.append(f"## {m['milestone_title']}\n")
            out.append(m["milestone_description"])

    return "\n\n".join(out).rstrip() + "\n"


def targets():
    """Yield (destination, wanted text) for every generated prose file."""
    for d in sorted(p for p in ROOT.iterdir()
                    if p.is_dir() and (p / "proposal.json").is_file()):
        yield d / "prose.md", prose_of(d.name)


def main(argv):
    check = "--check" in argv
    stale = []
    for dest, want in targets():
        if check:
            have = dest.read_text(encoding="utf-8") if dest.is_file() else ""
            if have != want:
                stale.append(str(dest.relative_to(ROOT.parent)))
                print(f"STALE  {dest}")
            else:
                print(f"ok     {dest}")
        else:
            dest.write_text(want, encoding="utf-8")
            print(f"wrote  {dest}  {len(want)} chars")
    if check and stale:
        print(f"\n{len(stale)} stale: {', '.join(stale)}. Run without --check.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
