import Mathlib

/-!
# Definition item: cube-free sets and layers in `ZMod (2^n)`

The one definition item of the `z2n-five-eighths` mission proposal. `p2m
item-add --kind definition` uploads this file whole, as the module
`Definitions.Def_Z2nCubeFreeLayers`, and every theorem item of the mission
imports it.

A definition item is a module rather than a declaration. The platform's own
corpus works that way: `Def_NgoRootDatumIsogeny` holds a structure and two
definitions, none of them named `NgoRootDatumIsogeny`. So `definition_name` is
the module name here and the six declarations below keep the names the
mathematics gives them.

Two encodings of the same forbidden configuration sit here side by side.
`HasCube` lists the seven memberships and `config` collects the same seven
elements into a `Finset` and asks for a subset. They are not definitionally
equal, because the `Finset` collapses duplicates when the triple is degenerate.
Proving them equivalent is a milestone of the mission, not an assumption of it.

Every binder is explicit. A `variable` line would be dropped when this file is
read for upload, and the module would arrive missing a hypothesis.

Ported on 2026-09-16 from `Workbench/Bench/z2n-five-eighths/Defs.lean`.
-/

namespace Z2nFiveEighths

/-- `HasCube A` says some triple `x, y, z` has all seven of its nonzero subset
sums inside `A`. The triple is unconstrained, so `x = y = z = 0` is allowed. -/
def HasCube {G : Type*} [AddCommGroup G] (A : Finset G) : Prop :=
  ∃ x y z : G, x ∈ A ∧ y ∈ A ∧ z ∈ A ∧
    x + y ∈ A ∧ y + z ∈ A ∧ z + x ∈ A ∧ x + y + z ∈ A

/-- `CubeFree A` is the hypothesis of the problem: `A` is free of affine
3-cubes. -/
def CubeFree {G : Type*} [AddCommGroup G] (A : Finset G) : Prop := ¬ HasCube A

/-- The forbidden 7-element configuration generated by `x`, `y`, `z`. As a
`Finset` this has fewer than seven elements when the triple is degenerate. -/
def config {G : Type*} [AddCommMonoid G] [DecidableEq G] (x y z : G) : Finset G :=
  {x, y, z, x + y, y + z, z + x, x + y + z}

/-- `A` is configuration free: no triple `x, y, z` has its whole configuration
inside `A`. The triple need not consist of distinct elements. -/
def ConfigFree {G : Type*} [AddCommMonoid G] [DecidableEq G] (A : Finset G) :
    Prop := ∀ x y z : G, ¬ config x y z ⊆ A

/-- The layer index of a residue mod `2^n`. -/
noncomputable def layerIdx (n : ℕ) (x : ZMod (2 ^ n)) : ℕ :=
  if x = 0 then n + 1 else padicValNat 2 x.val + 1

/-- `A` is a union of layers: whenever it contains one element of a layer it -/
def IsLayerUnion (n : ℕ) (A : Finset (ZMod (2 ^ n))) : Prop :=
  ∀ x y : ZMod (2 ^ n), x ∈ A → layerIdx n x = layerIdx n y → y ∈ A

end Z2nFiveEighths
